In [2]:
import numpy as np
x=np.array([1,2,3,4,5])   # less memory,faster,convinent use,mathematical operation
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
x=[1,2,3,4]
print(x)
print(type(x))

[1, 2, 3, 4]
<class 'list'>


In [6]:
%timeit [j**4 for j in range(1,9)]

1.09 µs ± 81.1 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [7]:
%timeit np.arange(1,9)**4

2.64 µs ± 108 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# create array

In [15]:
x=np.array([1,2,3,4,5])   
print(x)
x
print(x.ndim)

[1 2 3 4 5]
1


In [12]:
print(type(x))

<class 'numpy.ndarray'>


In [14]:
l=[]
for i in range(1,5):
    a=int(input("enter value"))
    l.append(a)
print(np.array(l))

enter value 2
enter value 3
enter value 4
enter value 5


[2 3 4 5]


# dimension array

In [16]:
x2=np.array([[1,2,3,4],[5,6,7,8]])
print(x2)
print(x2.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


In [18]:
x2=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(x2)
print(x2.ndim)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
3


In [22]:
ar_zero=np.zeros(4)
ar_zero1=np.zeros((3,4))
print(ar_zero)
print()
print(ar_zero1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [23]:
ar_one=np.ones(4)
ar_one1=np.ones((3,4))
print(ar_one)
print()
print(ar_one1)

[1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [24]:
ar_empty=np.empty(4)
print(ar_empty)

[1. 1. 1. 1.]


In [25]:
ar_ran=np.arange(4)
print(ar_ran)

[0 1 2 3]


In [26]:
ar_dia=np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [27]:
ar_dia=np.eye(3,5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [28]:
ar_lin=np.linspace(1,10,num=5)
ar_lin

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

# create by random functions

In [30]:
d=np.random.rand(4)
d    # random number

array([0.72968959, 0.54278784, 0.12335739, 0.88251296])

In [31]:
d=np.random.rand(4,5)
d

array([[0.10881577, 0.43934857, 0.68013909, 0.06738273, 0.08102559],
       [0.36063056, 0.33873059, 0.78567646, 0.91678126, 0.56178105],
       [0.00926255, 0.31109073, 0.26852118, 0.03296273, 0.93052815],
       [0.5741509 , 0.92749986, 0.95377997, 0.68092017, 0.36266681]])

In [32]:
d=np.random.randn(4)   #random number near to 0 both positive n negative
d

array([ 0.63441313, -1.0408631 , -1.21846285,  0.06364919])

In [33]:
d=np.random.ranf(4)     # random number [0.0,1.0)
d

array([0.56108138, 0.18234991, 0.66821133, 0.43768625])

In [34]:
d=np.random.randint(2,9,4)  # random number btw min max
d

array([6, 5, 5, 2])

# dataype

In [36]:
x=np.array([1,2,3,4,5])   
print(x.dtype)

int32


In [37]:
x=np.array([1.0,2.4,3.6,4.7,5.0])   
print(x.dtype)

float64


In [38]:
x=np.array(["a","b","c","d"])   
print(x.dtype)

<U1


In [39]:
x=np.array(["a","b","c","d",1,2,3,4,5])   
print(x.dtype)

<U11


In [40]:
x=np.array([1,2,3,4,5],dtype=np.int8)   
print(x.dtype)

int8


In [41]:
x=np.array([1,2,3,4,5],dtype="f")   
print(x.dtype)

float32


In [43]:
x=np.array([1,2,3,4,5])
new=np.float32(x)

print(x)
print(x.dtype)

print(new)
print(new.dtype)

[1 2 3 4 5]
int32
[1. 2. 3. 4. 5.]
float32


In [44]:
x=np.array([1,2,3,4,5])
x1=x.astype(float)
x1

array([1., 2., 3., 4., 5.])

# shape n reshape

In [45]:
x2=np.array([[1,2,3,4],[5,6,7,8]])
print(x2)
print(x2.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [54]:
x=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
v=x.reshape(3,4)
v1=x.reshape(2,3,2)

print(x.ndim)
print(v)
print(v.ndim)
print(v1)

1
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [55]:
one=v.reshape(-1)
print(one)
print(one.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


# arithmetic operation

In [63]:
x1=np.array([1,2,3,4])
x2=np.array([5,6,7,8])

x_add=np.add(x1,x2)
print(x_add)

[ 6  8 10 12]


In [65]:
x1=np.array([1,2,3,4])
x2=np.array([5,6,7,8])
x_sub=np.subtract(x1,x2)
print(x_sub)

[-4 -4 -4 -4]


In [66]:
x1=np.array([1,2,3,4])
x2=np.array([5,6,7,8])
x_mul=np.multiply(x1,x2)
print(x_mul)

[ 5 12 21 32]


In [67]:
x1=np.array([1,2,3,4])
x2=np.array([5,6,7,8])
x_div=np.divide(x1,x2)
print(x_div)

[0.2        0.33333333 0.42857143 0.5       ]


In [68]:
x1=np.array([1,2,3,4])
x2=np.array([5,6,7,8])
x_mod=np.mod(x1,x2)
print(x_mod)

[1 2 3 4]


In [69]:
x1=np.array([1,2,3,4])
x2=np.array([5,6,7,8])
x_pow=np.power(x1,x2)
print(x_pow)

[    1    64  2187 65536]


In [70]:
x1=np.array([1,2,3,4])
x_rec=np.reciprocal(x1)
print(x_rec)

[1 0 0 0]


In [75]:
x1=np.array([[1,2,3,4],[5,6,7,8]])
x2=np.array([[5,6,7,8],[1,2,3,4]])
x_add=np.add(x1,x2)
print(x1)
print()
print(x2)
print()
print(x_add)

[[1 2 3 4]
 [5 6 7 8]]

[[5 6 7 8]
 [1 2 3 4]]

[[ 6  8 10 12]
 [ 6  8 10 12]]


# max min argmin sqrt sin cos cumsum

In [82]:
x1=np.array([1,2,3,4])
print("max",np.max(x1))
print("position",np.argmax(x1))

max 4
position 3


In [83]:
x1=np.array([1,2,3,4])
print("min",np.min(x1))
print("position",np.argmin(x1))

min 1
position 0


In [87]:
x1=np.array([[1,2,3,4],[5,6,7,8]])  # column 1 and row 0
print(np.max(x1,axis=0))
print(np.max(x1,axis=1))

[5 6 7 8]
[4 8]


In [91]:
x1=np.array([1,2,3,4])
print(np.sqrt(x1))

[1.         1.41421356 1.73205081 2.        ]


In [93]:
x1=np.array([1,2,3,4])
print(np.sin(x1))
print(np.cos(x1))
print(np.cumsum(x1))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[ 1  3  6 10]


# broadcasting
error due to diff len of 2 array

In [6]:
import numpy as np
v1=np.array([1,2,3])
print(v1.shape)
print(v1)
print()
v2=np.array([[1],[2],[3]])
print(v2.shape)
print(v2)
print()
print(v1+v2)

(3,)
[1 2 3]

(3, 1)
[[1]
 [2]
 [3]]

[[2 3 4]
 [3 4 5]
 [4 5 6]]


# indexing n slicing

In [10]:
x=np.array([1,2,3,4,5,6])
print(x)
print(x.ndim)
print(x[5])

[1 2 3 4 5 6]
1
6


In [11]:
x=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(x)
print(x.ndim)
print(x[0,3])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
2
4


In [12]:
x=np.array([[[1,2,3,4,5,6],[7,8,9,10,11,12]]])
print(x)
print(x.ndim)
print(x[0,0,5])

[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]]]
3
6


In [16]:
x=np.array([1,2,3,4,5,6])
print(x[1::2])
print(x.ndim)

[2 4 6]
1


In [17]:
x=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(x[0,2:5])
print(x.ndim)

[3 4 5]
2


In [18]:
x=np.array([[[1,2,3,4,5,6],[7,8,9,10,11,12]]])
print(x[0,0,2:5])
print(x.ndim)

[3 4 5]
3


# iterating

In [19]:
x=np.array([1,2,3,4,5,6])
for i in x:
    print(i)

1
2
3
4
5
6


In [21]:
x=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
for i in x:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
9
10
11
12


In [23]:
x=np.array([[[1,2,3,4,5,6],[7,8,9,10,11,12]]])
for i in x:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
7
8
9
10
11
12


In [27]:
x=np.array([[[1,2,3,4,5,6],[7,8,9,10,11,12]]])
for i in np.nditer(x):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [26]:
x=np.array([[[1,2,3,4,5,6],[7,8,9,10,11,12]]])
for i in np.nditer(x,flags=["buffered"],op_dtypes=["S"]):
    print(i)

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'
b'9'
b'10'
b'11'
b'12'


In [28]:
x=np.array([[[1,2,3,4,5,6],[7,8,9,10,11,12]]])
for i,j in np.ndenumerate(x):
    print(i,j)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 0, 4) 5
(0, 0, 5) 6
(0, 1, 0) 7
(0, 1, 1) 8
(0, 1, 2) 9
(0, 1, 3) 10
(0, 1, 4) 11
(0, 1, 5) 12


# copy n view

In [29]:
x=np.array([1,2,3,4,5,6])
x1=x.copy()   
print(x)
print(x1)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [31]:
x=np.array([1,2,3,4,5,6])
x1=x.copy()      # new array and no change reflection
x[1]=100
print(x)
print(x1)

[  1 100   3   4   5   6]
[1 2 3 4 5 6]


In [30]:
x=np.array([1,2,3,4,5,6])
x1=x.view()    
print(x)
print(x1)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [32]:
x=np.array([1,2,3,4,5,6])
x1=x.view()     # original array and change reflectes
x[2]=300
print(x)
print(x1)

[  1   2 300   4   5   6]
[  1   2 300   4   5   6]


# join n split function 
same length to join

In [34]:
v=np.array([1,2,3,4])
v1=np.array([5,6,7,8])
a=np.concatenate((v,v1))
print(a)

[1 2 3 4 5 6 7 8]


In [36]:
v=np.array([[1,2],[3,4]])
v1=np.array([[5,6],[7,8]])
a=np.concatenate((v,v1),axis=1)
print(a)

[[1 2 5 6]
 [3 4 7 8]]


In [37]:
v=np.array([[1,2],[3,4]])
v1=np.array([[5,6],[7,8]])
a=np.concatenate((v,v1),axis=0)
print(a)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [38]:
v=np.array([[1,2],[3,4]])
v1=np.array([[5,6],[7,8]])
a=np.stack((v,v1),axis=0)
print(a)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [39]:
v=np.array([[1,2],[3,4]])
v1=np.array([[5,6],[7,8]])
a=np.stack((v,v1),axis=1)
print(a)

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [40]:
v=np.array([[1,2],[3,4]])
v1=np.array([[5,6],[7,8]])
a=np.hstack((v,v1))   #row
print(a)

[[1 2 5 6]
 [3 4 7 8]]


In [41]:
v=np.array([[1,2],[3,4]])
v1=np.array([[5,6],[7,8]])
a=np.vstack((v,v1))   #column
print(a)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [42]:
v=np.array([[1,2],[3,4]])
v1=np.array([[5,6],[7,8]])
a=np.dstack((v,v1))   #height
print(a)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [45]:
x=np.array([1,2,3,4,5,6])
a=np.array_split(x,3)
print(a)
print(type(a))
print(a[0])

[array([1, 2]), array([3, 4]), array([5, 6])]
<class 'list'>
[1 2]


In [46]:
x=np.array([[1,2],[3,4],[5,6]])
a=np.array_split(x,3)
print(a)
print(type(a))

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]
<class 'list'>


In [47]:
x=np.array([[1,2],[3,4],[5,6]])
a=np.array_split(x,3,axis=1)
print(a)
print(type(a))

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int32)]
<class 'list'>


# search sort search sorted filter

In [48]:
x=np.array([1,2,3,4,5,6,3,4,2,5,6,3,4,5])
a=np.where(x==2)
print(a)

(array([1, 8], dtype=int64),)


In [50]:
x=np.array([1,2,3,4,5,6,3,4,2,5,6,3,4,5])
a=np.where(x%2==0)
print(a)

(array([ 1,  3,  5,  7,  8, 10, 12], dtype=int64),)


In [51]:
x=np.array([1,2,3,4,5,6,7,8,9,10])
a=np.searchsorted(x,5)
print(a)

4


In [52]:
x=np.array([1,2,3,4,5,6,7,8,9,10])
a=np.searchsorted(x,5,side="right")
print(a)

5


In [54]:
x=np.array([1,2,3,4,5,6,3,4,2,5,6,3,4,5])
a=np.sort(x)
print(a)

[1 2 2 3 3 3 4 4 4 5 5 5 6 6]


In [55]:
x=np.array(["a","f","s","y","t","i"])
a=np.sort(x)
print(a)

['a' 'f' 'i' 's' 't' 'y']


In [56]:
x=np.array([[3,7,3],[2,7,4],[3,4,2],[5,6,3]])
a=np.sort(x)
print(a)

[[3 3 7]
 [2 4 7]
 [2 3 4]
 [3 5 6]]


In [58]:
x=np.array(["a","f","s","y"])
f=[True,False,True,False]
a=x[f]   # filter function
print(a)

['a' 's']


# shuffle unique resize flatten ravel

In [61]:
x=np.array([1,2,3,4,5,6])
np.random.shuffle(x)
print(x)

[6 4 2 1 3 5]


In [62]:
x=np.array([1,2,3,4,5,6,3,4,2,5,6,3,4,5])
a=np.unique(x)
print(a)

[1 2 3 4 5 6]


In [65]:
x=np.array([1,2,3,4,5,6,3,4,2,5,6,3,4,5])
a=np.unique(x,return_index=True,return_counts=True)
print(a)

(array([1, 2, 3, 4, 5, 6]), array([0, 1, 2, 3, 4, 5], dtype=int64), array([1, 2, 3, 3, 3, 2], dtype=int64))


In [66]:
x=np.array([1,4,5,6,3,4,2,5,6,3])
a=np.resize(x,(2,5))
print(a)

[[1 4 5 6 3]
 [4 2 5 6 3]]


In [69]:
print(a.flatten())    # by default c
print(a.ravel())

[1 4 5 6 3 4 2 5 6 3]
[1 4 5 6 3 4 2 5 6 3]


In [70]:
print(a.flatten(order="F"))    
print(a.ravel(order="F"))    

[1 4 4 2 5 5 6 6 3 3]
[1 4 4 2 5 5 6 6 3 3]


In [73]:
print(a.flatten(order="A"))  
print(a.ravel(order="A"))    

[1 4 5 6 3 4 2 5 6 3]
[1 4 5 6 3 4 2 5 6 3]


In [74]:
print(a.flatten(order="k"))
print(a.ravel(order="K"))    

[1 4 5 6 3 4 2 5 6 3]
[1 4 5 6 3 4 2 5 6 3]


# insert n delete

In [76]:
x=np.array([1,2,3,4,5,6])
a=np.insert(x,3,5)
print(a)

[1 2 3 5 4 5 6]


In [77]:
x=np.array([1,2,3,4,5,6])
a=np.insert(x,(3,4),5)
print(a)

[1 2 3 5 4 5 5 6]


In [78]:
x=np.array([1,2,3,4,5,6])
a=np.insert(x,(3,4),5.3)
print(a)

[1 2 3 5 4 5 5 6]


In [79]:
x=np.array([[1,2],[3,4],[5,6]])
a=np.insert(x,2,5,axis=0)
print(a)

[[1 2]
 [3 4]
 [5 5]
 [5 6]]


In [80]:
x=np.array([[1,2],[3,4],[5,6]])
a=np.insert(x,2,5,axis=1)
print(a)

[[1 2 5]
 [3 4 5]
 [5 6 5]]


In [81]:
x=np.array([[1,2],[3,4],[5,6]])
a=np.insert(x,2,[5,3,4],axis=1)
print(a)

[[1 2 5]
 [3 4 3]
 [5 6 4]]


In [83]:
x=np.array([1,2,3,4,5,6])
a=np.append(x,2)
print(a)

[1 2 3 4 5 6 2]


In [86]:
x=np.array([[1,2],[3,4],[5,6]])
a=np.append(x,[[4,5]],axis=0)
print(a)

[[1 2]
 [3 4]
 [5 6]
 [4 5]]


In [91]:
x=np.array([[1,2],[3,4],[5,6]])
a=np.append(x,[[4,3,4]],axis=1)
print(a)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 1

In [92]:
x=np.array([1,2,3,4,5,6])
d=np.delete(x,2)
print(d)

[1 2 4 5 6]


# matrix

In [93]:
x=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(x)
print(type(x))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.matrix'>


In [96]:
x=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
x1=np.matrix([[11,12,13],[14,15,16],[17,18,19]])
print(x+x1)
print()
print(x-x1)
print()
print(x*x1)
print()
print(x.dot(x1))

[[12 14 16]
 [18 20 22]
 [24 26 28]]

[[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]

[[ 90  96 102]
 [216 231 246]
 [342 366 390]]

[[ 90  96 102]
 [216 231 246]
 [342 366 390]]


In [99]:
x=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(np.transpose(x))
print()
print(x.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [100]:
x=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(np.swapaxes(x,0,1))

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [102]:
x=np.matrix([[1,2],[4,5]])
print(np.linalg.inv(x))

[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]


In [105]:
print(np.linalg.matrix_power(x,2))
print()
print(np.linalg.matrix_power(x,0))
print()
print(np.linalg.matrix_power(x,-2))

[[ 9 12]
 [24 33]]

[[1 0]
 [0 1]]

[[ 3.66666667 -1.33333333]
 [-2.66666667  1.        ]]


In [106]:
print(np.linalg.det(x))

-2.9999999999999996
